package Algo;
import java.util.Comparator;
import java.util.HashMap;
import java.util.PriorityQueue;

import Storage.ImageStorage;
public class Huffman {
    
    HashMap<Integer,String> HuffmandCode = new HashMap<>();
    HuffmanNode root = null;
    double huffmanLength;
    public int Calculate(int [][]imgArray){

        int[] level = pixelCount(imgArray);
        PriorityQueue<HuffmanNode> q = new PriorityQueue<HuffmanNode>(256, new MyComparator()); 
        
    for (int i = 0; i < level.length; i++) { 

        // creating a Huffman node object 
        // and add it to the priority queue. 
        HuffmanNode hn = new HuffmanNode(); 
        if(level[i]!=0)
        {
            hn.pixel = i; 
            hn.prob = level[i]; 

            hn.left = null; 
            hn.right = null; 

            // add functions adds 
            // the huffman node to the queue. 
            q.add(hn); 
        }
        
    } 

    // create a root node 
     

    // Here we will extract the two minimum value 
    // from the heap each time until 
    // its size reduces to 1, extract until 
    // all the nodes are extracted. 
    while (q.size() > 1) { 

        // first min extract. 
        HuffmanNode x = q.peek(); 
        q.poll(); 

        // second min extract. 
        HuffmanNode y = q.peek(); 
        q.poll(); 

        // new node f which is equal 
        HuffmanNode f = new HuffmanNode(); 

        // to the sum of the frequency of the two nodes 
        // assigning values to the f node. 
        f.prob = x.prob + y.prob; 
        f.pixel = -1; 

        // first extracted node as left child. 
        f.left = x; 

        // second extracted node as the right child. 
        f.right = y; 

        // marking the f node as the root node. 
        root = f; 

        // add this node to the priority-queue. 
        q.add(f); 
    }          
        this.printCode(root, "");
        return 0;
    }
    public double length(){
        return huffmanLength;

    }
    public int[] pixelCount(int imgArray[][]){
        int[] level = new int[256];
        for(int i=0;i<imgArray.length;i++){
            for(int j=0; j<imgArray[0].length;j++){
                level[imgArray[i][j]]+=1;
            }
        }
        return level;

    }
    class HuffmanNode{
        int prob;
        int pixel;
        HuffmanNode left;
        HuffmanNode right;
    }
    class MyComparator implements Comparator<HuffmanNode> { 
    public int compare(HuffmanNode x, HuffmanNode y) 
    { 
  
        return x.prob - y.prob; 
    } 
    }
    
    public void printCode(HuffmanNode root, String s) 
    { 
  
        // base case; if the left and right are null 
        // then its a leaf node and we print 
        // the code s generated by traversing the tree. 
        if (root.left == null && root.right == null
            && root.pixel>=0) { 
  
            // c is the character in the node 
            System.out.println(root.pixel + ":" + s); 
            HuffmandCode.put(root.pixel,"s");
            huffmanLength+=root.prob*s.length();
            return; 
        } 
  
        // if we go to left then add "0" to the code. 
        // if we go to the right add"1" to the code. 
  
        // recursive calls for left and 
        // right sub-tree of the generated tree. 
        printCode(root.left, s + "0"); 
        printCode(root.right, s + "1"); 
    } 


    public String[] PixelToCode(int[][] imgArray){
        String[] newArray = new String[imgArray.length];
        for(int i=0;i<imgArray.length;i++){
            for(int j=0; j<imgArray[0].length;j++){
                newArray[i*imgArray.length+j] = HuffmandCode.get(imgArray[i][j]);
            }
        }
        return newArray;
    }

    public int[] HuffmanDecoding(String[] newArray){
        int n = newArray.length;
        String ans;
        HuffmanNode curr = root;
        int[] HuffmanDecodeArray = new int[newArray.length];
       
        for(int i=0; i<n;i++){

            curr=root;
            for(int j =0; j<newArray[i].length();j++){
                if(curr.left ==null && curr.right == null){
            
                ans = newArray[i];
                }
                if(newArray[i] == "0"){
                    curr = curr.left;
                }else{
                    curr = curr.right;
                }
            }
            HuffmanDecodeArray[i]=curr.pixel;

        }
        
        return HuffmanDecodeArray;
    }

    


}
